import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Add the chatbot CSS style */}
        <style>
          {`
              #dify-chatbot-bubble-button {
                background-color: #1C64F2 !important;
              }
            `}
        </style>

        {/* Add chatbot configuration script */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
                window.difyChatbotConfig = {
                  token: '${process.env.NEXT_PUBLIC_DIFY_CHATBOT_TOKEN}',
                  baseUrl: '${process.env.NEXT_PUBLIC_DIFY_CHATBOT_BASE_URL}'
                }
              `,
          }}
        />

        {/* Add chatbot embed script */}
        <script
          src={`${process.env.NEXT_PUBLIC_DIFY_CHATBOT_BASE_URL}/embed.min.js`}
          id={process.env.NEXT_PUBLIC_DIFY_CHATBOT_TOKEN}
          defer
        />
      </body>
    </html>
  );
}
